name: Unity Build And Test
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '**'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{(github.event_name == 'pull_request' || github.event.action == 'synchronize')}}
jobs:
  build:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: ${{ matrix.unity-version }} ${{ matrix.build-target }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include: # for each os specify the build targets
          - os: ubuntu-latest
            unity-version: 2022.x
            build-target: StandaloneLinux64
          - os: ubuntu-latest
            unity-version: 6000.x
            build-target: StandaloneLinux64
          - os: ubuntu-latest
            unity-version: 2022.x
            build-target: WebGL
          - os: ubuntu-latest
            unity-version: 6000.x
            build-target: WebGL
          - os: ubuntu-latest
            unity-version: 2022.x
            build-target: Android
          - os: ubuntu-latest
            unity-version: 6000.x
            build-target: Android
          - os: ubuntu-latest
            unity-version: 2022.x
            build-target: iOS
          - os: ubuntu-latest
            unity-version: 6000.x
            build-target: iOS
          - os: windows-latest
            unity-version: 2022.x
            build-target: StandaloneWindows64
          - os: windows-latest
            unity-version: 6000.x
            build-target: StandaloneWindows64
          - os: macos-latest
            unity-version: 2022.x
            build-target: StandaloneOSX
          - os: macos-latest
            unity-version: 6000.x
            build-target: StandaloneOSX
    steps:
      - uses: actions/checkout@v4
      - uses: RageAgainstThePixel/unity-setup@v1
        with:
          unity-version: ${{ matrix.unity-version }}
          build-targets: ${{ matrix.build-target }}
      - uses: RageAgainstThePixel/activate-unity-license@v1
        with:
          license: 'Personal'
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
      - uses: RageAgainstThePixel/unity-action@v1
        name: '${{ matrix.build-target }}-Validate'
        with:
          log-name: '${{ matrix.build-target }}-Validate'
          build-target: ${{ matrix.build-target }}
          args: '-quit -nographics -batchmode -executeMethod Utilities.Editor.BuildPipeline.UnityPlayerBuildTools.ValidateProject -importTMProEssentialsAsset'
      - uses: RageAgainstThePixel/unity-action@v1
        name: '${{ matrix.build-target }}-Test'
        with:
          log-name: '${{ matrix.build-target }}-Test'
          build-target: ${{ matrix.build-target }}
          args: '-nographics -batchmode -runTests -testPlatform EditMode -testResults "${{ github.workspace }}/Logs/${{ matrix.build-target }}-results.xml"'
      - uses: RageAgainstThePixel/unity-action@v1
        name: '${{ matrix.build-target }}-Build'
        with:
          log-name: '${{ matrix.build-target }}-Build'
          build-target: ${{ matrix.build-target }}
          args: '-quit -nographics -batchmode -executeMethod Utilities.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild'
      - uses: RageAgainstThePixel/unity-test-summary@v1
        if: success() || failure()
        with:
          test-results: ${{ github.workspace }}/**/*-results.xml
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          compression-level: 0
          retention-days: 1
          name: '${{ github.run_number }}.${{ github.run_attempt }}-${{ matrix.os }}-${{ matrix.unity-version }}-${{ matrix.build-target }}-Artifacts'
          path: |
            ${{ github.workspace }}/**/*.log
