name: UPM Release
on:
  push:
    branches: [main]
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: RageAgainstThePixel/upm-release@v2
      with:
        organization-id: ${{ secrets.UNITY_ORG_ID }}
        upm-service-account-key-id: ${{ secrets.UPM_SERVICE_ACCOUNT_KEY_ID }}
        upm-service-account-key-secret: ${{ secrets.UPM_SERVICE_ACCOUNT_KEY_SECRET }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
